# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: '#about'
    weight: 13
  - name: Works
    url: '#experience'
    weight: 26
  - name: Working-On
    url: '#projects'
    weight: 39
  - name: Published
    url: '#publications'
    weight: 52
  - name: Contact
    url: '#contact'
    weight: 65

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/uploads/resume.pdf` and uncomment the lines below.
#  - name: CV
#    url: uploads/resume.pdf
#    weight: 70
